version: "3"

networks:
  obs_stack:

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    networks:
      - obs_stack

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - obs_stack

  prometheus:
    image: prom/prometheus
    command: [ "--web.enable-remote-write-receiver", "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ./configs/prometheus/prometheus-config.yaml:/etc/prometheus.yaml
      - prometheus_data:/prometheus
    networks:
      - obs_stack

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/tempo/tempo-config.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    networks:
      - obs_stack

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=file:/etc/otel.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./tsl_certificates/server.crt:/server.crt
      - ./tsl_certificates/server.key:/server.key
      - ./configs/otel/otel-config.yaml:/etc/otel.yaml
    networks:
      - obs_stack

volumes:
  grafana_data:
  loki_data:
  prometheus_data:
  tempo_data:
