version: "3"

networks:
  obs_stack:

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    networks:
      - obs_stack

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - obs_stack

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus

volumes:
  grafana_data:
  loki_data:
  prometheus_data:
