receivers:
  otlp:
    protocols:
      grpc:
        tls:
          cert_file: /server.crt
          key_file: /server.key
      http:
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: 'opentelemetry-collector'
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    add_metric_suffixes: true
  otlphttp:
    endpoint: http://tempo:4418
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  logging/metrics:
    verbosity: detailed
  logging/traces:
    verbosity: detailed
  logging/logs:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
      #exporters: [otlphttp,logging/traces]
    metrics:
      receivers: [otlp,prometheus/collector]
      processors: [batch]
      exporters: [prometheusremotewrite]
      #exporters: [prometheusremotewrite,logging/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
      #exporters: [loki,logging/logs]